'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FTTTTTT")>  _
        Public Property DayIndex() As String
            Get
                Return CType(Me("DayIndex"),String)
            End Get
            Set
                Me("DayIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FFFFFFT")>  _
        Public Property DiffDay() As String
            Get
                Return CType(Me("DiffDay"),String)
            End Get
            Set
                Me("DiffDay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N:\")>  _
        Public Property BaseLocation() As String
            Get
                Return CType(Me("BaseLocation"),String)
            End Get
            Set
                Me("BaseLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N:\Completed")>  _
        Public Property CompletedLocation() As String
            Get
                Return CType(Me("CompletedLocation"),String)
            End Get
            Set
                Me("CompletedLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property NumSurveys() As Integer
            Get
                Return CType(Me("NumSurveys"),Integer)
            End Get
            Set
                Me("NumSurveys") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FTTTTTT,FFFFFFT,N:\,N:\Completed,9,\Surveys.xlsm,\setings.ntd,\Route_Run.csv,N\Cr"& _ 
            "eated")>  _
        Public Property Defaults() As String
            Get
                Return CType(Me("Defaults"),String)
            End Get
            Set
                Me("Defaults") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2018-07-06")>  _
        Public Property SetDat() As Date
            Get
                Return CType(Me("SetDat"),Date)
            End Get
            Set
                Me("SetDat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Surveys.xlsm")>  _
        Public Property SurveyFileName() As String
            Get
                Return CType(Me("SurveyFileName"),String)
            End Get
            Set
                Me("SurveyFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("setings.ntd")>  _
        Public Property SettingsFileName() As String
            Get
                Return CType(Me("SettingsFileName"),String)
            End Get
            Set
                Me("SettingsFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Route_Run.csv")>  _
        Public Property RouteRunFileName() As String
            Get
                Return CType(Me("RouteRunFileName"),String)
            End Get
            Set
                Me("RouteRunFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WDSurveyBatch.csv")>  _
        Public Property WeekdayBatchFileName() As String
            Get
                Return CType(Me("WeekdayBatchFileName"),String)
            End Get
            Set
                Me("WeekdayBatchFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WESurveyBatch.csv")>  _
        Public Property WeekendBatchFileName() As String
            Get
                Return CType(Me("WeekendBatchFileName"),String)
            End Get
            Set
                Me("WeekendBatchFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N:\Created")>  _
        Public Property CreatedLocation() As String
            Get
                Return CType(Me("CreatedLocation"),String)
            End Get
            Set
                Me("CreatedLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SurveyTotals.xlsx")>  _
        Public Property TotalFile() As String
            Get
                Return CType(Me("TotalFile"),String)
            End Get
            Set
                Me("TotalFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5:00")>  _
        Public Property AMPeak() As String
            Get
                Return CType(Me("AMPeak"),String)
            End Get
            Set
                Me("AMPeak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10:30")>  _
        Public Property Afternoon() As String
            Get
                Return CType(Me("Afternoon"),String)
            End Get
            Set
                Me("Afternoon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14:00")>  _
        Public Property PMPeak() As String
            Get
                Return CType(Me("PMPeak"),String)
            End Get
            Set
                Me("PMPeak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VehicleCapacity.csv")>  _
        Public Property VehCapFile() As String
            Get
                Return CType(Me("VehCapFile"),String)
            End Get
            Set
                Me("VehCapFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AudibleNotificationsEnabled() As Boolean
            Get
                Return CType(Me("AudibleNotificationsEnabled"),Boolean)
            End Get
            Set
                Me("AudibleNotificationsEnabled") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.NTD_System.My.MySettings
            Get
                Return Global.NTD_System.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
